#!/bin/bash
# Twilight ISO Downloader - Quick Reference Guide

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║           Twilight ISO Downloader - Quick Start                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "✓ Requirements installed successfully!"
echo ""
echo "📚 USAGE EXAMPLES:"
echo ""
echo "1️⃣  Interactive menu (easiest):"
echo "   ./start.sh"
echo ""
echo "2️⃣  Download everything:"
echo "   source venv/bin/activate && python download_twilight.py"
echo ""
echo "3️⃣  Download only ISO files:"
echo "   source venv/bin/activate && python download_twilight.py --types iso"
echo ""
echo "4️⃣  Download only ISO and BIN files:"
echo "   source venv/bin/activate && python download_twilight.py --types iso bin"
echo ""
echo "5️⃣  Download cover images (no thumbnails):"
echo "   source venv/bin/activate && python download_twilight.py --types jpg --skip-thumbs"
echo ""
echo "6️⃣  Download to specific directory:"
echo "   source venv/bin/activate && python download_twilight.py --output /path/to/save"
echo ""
echo "7️⃣  Get help:"
echo "   source venv/bin/activate && python download_twilight.py --help"
echo ""
echo "⚠️  IMPORTANT NOTES:"
echo "   • The full collection is 500+ GB - ensure you have space!"
echo "   • Downloads can be resumed if interrupted (Ctrl+C)"
echo "   • Files are saved to './downloads' by default"
echo "   • Always activate venv first: source venv/bin/activate"
echo ""
echo "📁 FILE TYPES AVAILABLE:"
echo "   • iso  - Disc images (640MB - 8GB each)"
echo "   • bin  - Binary disc images"
echo "   • jpg  - Cover art"
echo "   • xml  - Metadata"
echo ""
echo "🚀 READY TO START!"
echo ""
